//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventoryForServiceItem
    {
        public long Id { get; set; }
        public string Model { get; set; }
        public string IMEI1 { get; set; }
        public string IMEI2 { get; set; }
        public string WO { get; set; }
        public string Project { get; set; }
        public string Color { get; set; }
        public string EanCode { get; set; }
        public string Sn { get; set; }
        public string Bt { get; set; }
        public string Wifi { get; set; }
        public string SubSn { get; set; }
        public Nullable<bool> IsInventoryIn { get; set; }
        public Nullable<System.DateTime> IsInventoryInDate { get; set; }
        public Nullable<bool> IsInventoryOut { get; set; }
        public Nullable<System.DateTime> IsInventoryOutDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
